install.packages("swirl")
library("swirl")
swirl()

library(forecast)
install.packages("forecast")
library(forecast)
library(ggplot2)
autoplot(gold)
which.max(gold)
ggseasonplot(forecast::gas)
ggseasonplot(window(gas,start=1990))
ggseasonplot(window(gas,start=1990),polar = TRUE)
ggsubseriesplot(gas)
forecast::findfrequency(gas)
